### ISSUE TITLE
MXE fails to find_package

### ISSUE THREAD

**Issue by ADRFranklin** [mxe/mxe#2379]
Hi, I want to state that I am in no way a pro at cmake (I learned it 6 hours ago, came from makefile) and I noticed an issue that seems to be common here.

I am currently using dockcross to cross compile using docker, and after hours of playing around learning cmake and getting to build, I found an issue when using MXE.

On the exact same repo compiling with Linux, cmake is able to find_package perfectly with no issues, yet on the same repo again on MXE it fails to find the package.

as a work around I had to skip using find_package on anything but UNIX. MXE would also throw this error
```
CMake Error at /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SAMPSDK (missing: SAMPSDK_DIR SAMPSDK_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  lib/cmake-modules/FindSAMPSDK.cmake:21 (find_package_handle_standard_args)
  src/CMakeLists.txt:5 (find_package)
```

and this is the repo used for this https://github.com/Zeex/cmake-modules
(the one used is FindSAMPSDK.cmake)

am I missing anything that is specific to the way MXE cmake works? Like are there any extra steps or different constants I need to use to get it to work? Or is this a bug?

I assumed it was a bug, since it works fine on the Linux version.

here is my `gitlab-ci` file used to build it

```
stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:linux:
  image: dockcross/linux-x86:latest
  stage: build
  script:     
    - cmake .
    - make
  artifacts:
    paths:
      - src/community-anticheat.so 
      
build:windows:
  image: dockcross/windows-static-x86:latest
  stage: build
  script:     
    - cmake .
    - make
  artifacts:
    paths:
      - src/community-anticheat.dll 
```

I am still new to this process of building, and if you need more details, I will be happy to do my best to provide them.

I have used a work around to get this to work for me, so I am not posting this to fix my issue, I am posting this to make sure the developers are aware of this issue, and so that I may help in it being fixed if that is the case.
